package Fabio.Gilardi.CapstoneBE.enums;

public enum AccessoryName {
    ALLOY_WHEELS, SPORT_SETUP, ELECTRIC_SEATS, DUAL_ZONE_AIR_CONDITIONING, PANORAMIC_ROOF, ASSISTED_PARKING, DASHCAM, SENSORS, CRUISE_CONTROL, RUNFLAT_TYRES, SPARE_WHEEL, EMERGENCY_KIT, FULL_LED_HEADLIGHTS
}
